### PR TITLE
Modify OTPKit repo to Swift Package

### LINKED ISSUE #45: Swift Package Manager Support
I'd like to see OTPKit become an SPM package. There's some good documentation on the process here: https://www.avanderlee.com/swift/creating-swift-package-manager-framework/

### PR DESCRIPTION
**Pull request by hilmyveradin**
## Description
Make the whole repo as Swift Package

## Related Issues
Fixes #45 

## Test Instructions

Please describe the tests that you ran to verify your changes. Provide instructions so others can reproduce.

1. Try the demo project
2. See if the OTPKit is integrated correctly

## Additional Context

- XCodegen is removed to make it more simple if people want to use it. They can go straight to the demo project without generating the xcodeproj file
- gitignore for xcodeproj and pbxproj file is also removed

### CODE REVIEW

**Review by aaronbrethorst — APPROVED** [review]
nice work!

**Review by aaronbrethorst — CHANGES_REQUESTED** [review]
nice work! Before this gets merged, though, the tests need to be restored and the CI needs to be fixed. let me know if you need help with either

**Comment by hilmyveradin** [comment]
> nice work! Before this gets merged, though, the tests need to be restored and the CI needs to be fixed. let me know if you need help with either

Understood! About the test, should I restore the test for the demo app or the package?

**Comment by aaronbrethorst** [comment]
Package if that's possible

**Review by aaronbrethorst — APPROVED** [review]
👍

**Pull request merged**
